version: "3.7"

services:
  app_mongo:
    container_name: app_mongo
    restart: always
    build: .
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_DIR: ${MONGO_DIR}
      SERVER_DID: ${SERVER_DID}
      SERVER_PRIVATE_KEY: ${SERVER_PRIVATE_KEY}
      MOURO_URL: ${MOURO_URL}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      TWILIO_SID: ${TWILIO_SID}
      TWILIO_TOKEN: ${TWILIO_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      PHONE_REGION: ${PHONE_REGION}
      DEBUGG_MODE: ${PHONE_REGION}
      MONGO_PORT: ${MONGO_PORT}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.2.1
    command: mongod --port ${MONGO_PORT}
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
